# Use normal equation to compute the parameters
# Compare the results with one generated by gradient descent.

# to be solved: the bias item for the normalEqn
import numpy as np
import featureNormalize

def normalEqn(x, y):
    x = featureNormalize.normalize(x, 2)
    return np.dot(np.dot(np.linalg.inv(np.dot(np.transpose(x), x)), np.transpose(x)), y)
